### PR TITLE
'clipPadding' property for TitleFlowIndicator is introduced. 

### PR DESCRIPTION
**Pull request by iboyko**
Integer value that is defined by the property is used on the left side of the left view title and on the right side of the right view title so the views can have padding to the border to the parent view. Default value is 0. 

'clipPadding' can be defined as attribute in xml layout see title_with_padding_layout.xml in viewflow_example project.

### CODE REVIEW

**Comment by pakerfeldt** [comment]
Perfect. Would it be possible for you to just commit the TitleFlowIndicator.java and attrs.xml? I rather include an example of your padding in the already existing TitleFlowIndicatorExample (instead of creating a new activity).

**Comment by iboyko** [comment]
Last commit contains only files specified by you with comment on added methods and attribute.

**Comment by pakerfeldt** [comment]
I still depend on your first commit for changes made in TitleFlowIndicator.java, though. I'm no git pro so I don't know if it's possible to cherry pick certain files from a commit.

I see two alternatives. 
1. I merge your changes manually (it's not that much) but that would erase commit history and put my name on your contribution, or 
2. You do a fresh new pull request with all changes necessary only to TitleFlowIndicator.java, attrs.xml (and possibly title_layout.xml in order to add the clipPadding attribute), and I pull in that one instead. That would keep your name in the commit history.

What do you prefer?

**Comment by iboyko** [comment]
Second pull request is created #22 that contains only TitleFlowIndicator.java,  attrs.xml and title_layout.xml

**Pull request closed without merging**
